# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69675f06df908408d4797d1193469c14"
name = "cloudship"
application_url = "https://backend-cloud-jzom.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "clouship-test.myshopify.com"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,read_shipping,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://backend-cloud-jzom.onrender.com/api/auth/callback"
]

[pos]
embedded = false
